export type WorldPortsData = {
    [country: string]: string[];
};

export const WORLD_PORTS_BY_COUNTRY: WorldPortsData = {
    // ─── AFRIQUE ──────────────────────────────────────
    "Afrique du Sud": ["Le Cap", "Durban", "Port Elizabeth", "East London", "Richards Bay", "Mossel Bay", "Saldanha Bay"],
    "Algérie": ["Alger", "Oran", "Annaba", "Béjaïa", "Skikda", "Arzew", "Mostaganem", "Ghazaouet"],
    "Angola": ["Luanda", "Lobito", "Namibe", "Cabinda", "Soyo"],
    "Bénin": ["Cotonou"],
    "Cameroun": ["Douala", "Limbé", "Kribi"],
    "Congo (Brazzaville)": ["Pointe-Noire"],
    "Congo (RDC)": ["Matadi", "Boma", "Banana"],
    "Côte d'Ivoire": ["Abidjan", "San-Pédro"],
    "Djibouti": ["Djibouti", "Port de Doraleh"],
    "Egypte": ["Alexandrie", "Port-Saïd", "Suez", "Damiette", "Sokhna", "Safaga"],
    "Erythrée": ["Massawa", "Assab"],
    "Ethiopia": ["Djibouti (transit)"],
    "Gabon": ["Libreville", "Port-Gentil", "Owendo"],
    "Ghana": ["Tema", "Takoradi"],
    "Guinée": ["Conakry"],
    "Guinée équatoriale": ["Malabo", "Bata"],
    "Kenya": ["Mombasa", "Lamu"],
    "Libéria": ["Monrovia", "Buchanan"],
    "Libye": ["Tripoli", "Benghazi", "Misrata", "Ras Lanouf", "Az-Zawiya"],
    "Madagascar": ["Toamasina", "Mahajanga", "Toliara", "Antsiranana"],
    "Maroc": ["Tanger Med", "Casablanca", "Agadir", "Nador", "Mohammedia", "Laâyoune", "Dakhla"],
    "Maurice": ["Port Louis"],
    "Mauritanie": ["Nouakchott", "Nouadhibou"],
    "Mozambique": ["Maputo", "Beira", "Nacala", "Quelimane"],
    "Namibie": ["Walvis Bay", "Lüderitz"],
    "Nigéria": ["Lagos (Apapa)", "Tin Can Island", "Onne", "Warri", "Calabar", "Port Harcourt"],
    "Sénégal": ["Dakar", "Kaolack"],
    "Sierra Leone": ["Freetown"],
    "Somalie": ["Mogadiscio", "Berbera", "Kismayo", "Bosasso"],
    "Soudan": ["Port-Soudan"],
    "Tanzanie": ["Dar es Salaam", "Zanzibar", "Tanga", "Mtwara"],
    "Togo": ["Lomé"],
    "Tunisie": ["Tunis-Rades", "Sfax", "Sousse", "Bizerte", "La Skhirra", "Gabes"],

    // ─── ASIE ─────────────────────────────────────────
    "Arabie Saoudite": ["Djeddah", "Dammam (King Abdulaziz)", "Yanbu", "Jubail", "Riyad (sec)"],
    "Azerbaïdjan": ["Bakou"],
    "Bahreïn": ["Khalifa bin Salman"],
    "Bangladesh": ["Chittagong", "Mongla"],
    "Chine": ["Shanghai", "Shenzhen (Yantian)", "Ningbo", "Guangzhou (Nansha)", "Tianjin", "Qingdao", "Dalian", "Xiamen", "Lianyungang", "Nanjing", "Wuhan", "Chongqing", "Taicang"],
    "Corée du Sud": ["Busan", "Incheon", "Gwangyang", "Ulsan", "Pohang"],
    "Émirats arabes unis": ["Dubaï (Jebel Ali)", "Abou Dhabi (Khalifa)", "Charjah", "Fujairah", "Ras Al Khaimah"],
    "Hong Kong": ["Hong Kong"],
    "Inde": ["Mumbai (JNPT)", "Chennai (Madras)", "Kolkata", "Cochin", "Visakhapatnam", "Mundra", "Kandla", "Hazira", "Tuticorin", "Paradip", "Haldia"],
    "Indonésie": ["Jakarta (Tanjung Priok)", "Surabaya (Tanjung Perak)", "Belawan", "Makassar", "Balikpapan", "Semarang", "Palembang"],
    "Irak": ["Oum Qasr", "Bassora"],
    "Iran": ["Bandar Abbas (Shahid Rajaee)", "Imam Khomeini", "Chabahar", "Bushehr", "Bandar Anzali"],
    "Israël": ["Haïfa", "Ashdod", "Eilat"],
    "Japon": ["Tokyo", "Yokohama", "Osaka", "Kobé", "Nagoya", "Hakata", "Kitakyushu", "Chiba", "Hiroshima"],
    "Jordanie": ["Aqaba"],
    "Kazakhstan": ["Aktau"],
    "Koweït": ["Shuwaikh", "Shuaiba", "Doha (Koweït)"],
    "Liban": ["Beyrouth", "Tripoli"],
    "Malaisie": ["Port Klang", "Tanjung Pelepas (PTP)", "Penang", "Johor", "Kuching", "Kota Kinabalu"],
    "Maldives": ["Malé"],
    "Myanmar": ["Yangon", "Thilawa"],
    "Oman": ["Mascate (Sultan Qaboos)", "Salalah", "Sohar", "Duqm"],
    "Pakistan": ["Karachi", "Port Qasim", "Gwadar"],
    "Philippines": ["Manille", "Cebu", "Davao", "Subic Bay", "Cagayan de Oro"],
    "Qatar": ["Doha (Hamad Port)"],
    "Singapour": ["Singapour (Tuas)", "Singapour (Brani)", "Singapour (Pasir Panjang)"],
    "Sri Lanka": ["Colombo", "Hambantota"],
    "Taïwan": ["Kaohsiung", "Taichung", "Keelung"],
    "Thaïlande": ["Bangkok (Laem Chabang)", "Map Ta Phut", "Songkhla"],
    "Turquie": ["Istanbul (Ambarli)", "Izmir", "Mersin", "Gemlik", "Iskenderun", "Derince", "Trabzon"],
    "Vietnam": ["Hô Chi Minh-Ville (Cai Mep)", "Haïphong", "Danang", "Quy Nhon"],
    "Yémen": ["Aden", "Hodeïda", "Mukalla"],

    // ─── EUROPE ───────────────────────────────────────
    "Albanie": ["Durrës", "Vlorë", "Sarandë"],
    "Allemagne": ["Hambourg", "Brême", "Bremerhaven", "Rostock", "Kiel", "Lubeck"],
    "Belgique": ["Anvers", "Zeebruges", "Gand"],
    "Bulgarie": ["Varna", "Bourgas"],
    "Croatie": ["Rijeka", "Split", "Ploče", "Dubrovnik", "Zadar"],
    "Danemark": ["Copenhague", "Aarhus", "Esbjerg", "Fredericia", "Aalborg"],
    "Espagne": ["Valence", "Barcelone", "Algésiras", "Bilbao", "Vigo", "Las Palmas", "Santa Cruz de Tenerife", "Barcelone", "Tarragone"],
    "Estonie": ["Tallinn", "Sillamäe"],
    "Finlande": ["Helsinki", "Kotka", "Turku", "Rauma", "Hamina"],
    "France": ["Le Havre", "Marseille-Fos", "Dunkerque", "Nantes-Saint-Nazaire", "La Rochelle", "Bordeaux", "Sète", "Rouen"],
    "Géorgie": ["Batumi", "Poti", "Koulevi"],
    "Grèce": ["Le Pirée", "Thessalonique", "Patras", "Héraklion", "Volos", "Cavala"],
    "Irlande": ["Dublin", "Cork", "Shannon Foynes", "Waterford"],
    "Islande": ["Reykjavik", "Akureyri", "Hafnarfjördur"],
    "Italie": ["Gênes", "La Spezia", "Naples (Salerne)", "Trieste", "Venise (Marghera)", "Livourne", "Gioia Tauro", "Tarente", "Palerme"],
    "Lettonie": ["Riga", "Ventspils", "Liepāja"],
    "Lituanie": ["Klaïpeda"],
    "Malte": ["Marsaxlokk (Malta Freeport)", "La Valette"],
    "Monténégro": ["Bar"],
    "Norvège": ["Oslo", "Bergen", "Stavanger", "Ålesund", "Kristiansand"],
    "Pays-Bas": ["Rotterdam", "Amsterdam", "Flessingue (Zeeland Seaports)"],
    "Pologne": ["Gdańsk", "Gdynia", "Szczecin", "Świnoujście"],
    "Portugal": ["Lisbonne (Alcântara)", "Sines", "Leixões (Porto)", "Setúbal", "Aveiro", "Figueira da Foz"],
    "Roumanie": ["Constanţa"],
    "Royaume-Uni": ["Felixstowe", "Southampton", "Londres (Tilbury)", "Liverpool", "Bristol (Avonmouth)", "Glasgow", "Belfast", "Immingham"],
    "Russie": ["Saint-Pétersbourg", "Novorossiïsk", "Vladivostok", "Mourmansk", "Nakhodka", "Vostochny"],
    "Slovénie": ["Koper"],
    "Suède": ["Göteborg", "Stockholm", "Malmö", "Helsingborg", "Gävle"],
    "Ukraine": ["Odessa", "Illichivsk", "Tchornoморsk"],

    // ─── AMÉRIQUES ────────────────────────────────────
    "Argentine": ["Buenos Aires", "Bahía Blanca", "Rosario", "Mar del Plata", "Dock Sud"],
    "Bolivie": ["Arica (transit Chili)", "Ilo (transit Pérou)"],
    "Brésil": ["Santos", "Itajaí", "Paranaguá", "Suape", "Rio de Janeiro", "Salvador (Bahia)", "Fortaleza", "Vitória", "Belém", "Manaus", "Recife", "Rio Grande"],
    "Canada": ["Vancouver", "Halifax", "Montréal", "Prince Rupert", "Saint-Jean (NB)", "Hamilton"],
    "Chili": ["Valparaíso", "San Antonio", "Iquique", "Antofagasta", "Puerto Montt", "San Vicente (Talcahuano)"],
    "Colombie": ["Carthagène", "Barranquilla", "Buenaventura", "Santa Marta", "Turbo"],
    "Costa Rica": ["Puerto Limón", "Puerto Caldera"],
    "Cuba": ["La Havane", "Santiago de Cuba", "Mariel", "Cienfuegos"],
    "Équateur": ["Guayaquil", "Puerto Bolívar"],
    "États-Unis": ["Los Angeles", "Long Beach", "New York / New Jersey", "Houston", "Savannah", "Seattle", "Oakland", "Baltimore", "Charleston", "Miami", "Tacoma", "La Nouvelle-Orléans", "Jacksonville", "Norfolk (Hampton Roads)", "Boston"],
    "Guatemala": ["Santo Tomás de Castilla", "Puerto Quetzal"],
    "Haïti": ["Port-au-Prince", "Cap-Haïtien"],
    "Honduras": ["Puerto Cortés", "La Ceiba"],
    "Jamaïque": ["Kingston", "Montego Bay"],
    "Mexique": ["Manzanillo", "Veracruz", "Lázaro Cárdenas", "Altamira", "Mazatlán", "Ensenada", "Guaymas"],
    "Nicaragua": ["Corinto", "Puerto Sandino"],
    "Panama": ["Colón", "Balboa", "Manzanillo (Panamá)", "Cristóbal"],
    "Paraguay": ["Asunción (fluvial)", "Villeta (fluvial)"],
    "Pérou": ["Callao", "Paita", "Matarani", "Ilo", "Salaverry"],
    "République Dominicaine": ["Santo Domingo", "Caucedo", "Puerto Plata", "Haina"],
    "Salvador": ["Acajutla", "La Unión"],
    "Trinidad-et-Tobago": ["Port of Spain", "Point Lisas", "Scarborough"],
    "Uruguay": ["Montevideo", "Nueva Palmira", "Fray Bentos"],
    "Venezuela": ["La Guaira", "Puerto Cabello", "Maracaibo", "Puerto Ordaz", "Barcelona (Vénézuéla)"],

    // ─── OCÉANIE ──────────────────────────────────────
    "Australie": ["Sydney (Botany Bay)", "Melbourne", "Brisbane", "Fremantle (Perth)", "Adélaïde", "Darwin"],
    "Fidji": ["Suva", "Lautoka"],
    "Nouvelle-Zélande": ["Auckland", "Wellington", "Tauranga", "Lyttelton (Christchurch)", "Napier"],
    "Papouasie-Nouvelle-Guinée": ["Port Moresby", "Lae", "Rabaul"],
    "Vanuatu": ["Port Vila", "Luganville"],
};

export const MARITIME_COUNTRIES = Object.keys(WORLD_PORTS_BY_COUNTRY).sort((a, b) =>
    a.localeCompare(b, "fr")
);
